version: "3.9"
services:
  web:
    build: .
    environment:
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_PUBLIC_BASE_URL=${R2_PUBLIC_BASE_URL}

